name: dnrule Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:
  dnrule:
    runs-on: ubuntu-latest
    steps:
      - name: dnrule
        uses: zxcv9203/dnRule@test1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}