name: dnrule Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  issues: write
jobs:
  dnrule:
    runs-on: ubuntu-latest
    steps:
      - name: dnrule
        uses: zxcv9203/dnRule@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ secrets.GITHUB_REPOSITORY }}