name: dnrule Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  dnrule:
    runs-on: ubuntu-latest
    steps:
      - name: dnrule
        uses: zxcv9203/dnRule@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}